#!/bin/bash

#current_brightness=$(brightnessctl | awk 'NR==2 {print $3}')
current_brightness=$(brightnessctl g)

if [[ $current_brightness -le 96000 ]]; then
	final_brightness=$((current_brightness + 3840))
	brightnessctl -d intel_backlight set "$final_brightness"
fi

new_brightness=$(brightnessctl g)
pb=$(((new_brightness * 100) / 96000)) # percentage brightness

#dunstify -r 9999 "$((percentage_brightness))%" -h int:value:100
notify-send -h int:value:$((pb)) -h string:synchronous:progress "󰃠 "
