#!/bin/bash

# Script to decrease screen brightness

current_brightness=$(brightnessctl g)

if [[ $current_brightness -ge 4000 ]]; then
	final_brightness=$((current_brightness - 3840))
	brightnessctl -d intel_backlight set "$final_brightness"
fi

new_brightness=$(brightnessctl g)
pb=$(((new_brightness * 100) / 96000)) # percentage brightness

notify-send -h int:value:$((pb)) -h string:synchronous:progress "󰃠 "

